OSBB/Controllers/BenefitController.cs
using OSBB_BLL.Models;
using OSBB_BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OSBB.Controllers
{
    [Authorize(Roles = "OSBB_Admin")]
    public class BenefitController : Controller
    {
        IGenericService<BenefitDTO> benefitService;

        public BenefitController(IGenericService<BenefitDTO> benefitService)
        {
            this.benefitService = benefitService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(benefitService.GetAll());
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            BenefitDTO benefit = (id == 0) ? new BenefitDTO() : benefitService.Get(id);
            return View(benefit);
        }

        [HttpPost]
        public ActionResult Edit(BenefitDTO benefit)
        {
            if (ModelState.IsValid)
            {
                benefitService.AddOrUpdate(benefit);
                return RedirectToAction("Index");
            }
            return View(benefit);
        }

        [HttpPost]
        public ActionResult Delete (int id)
        {
            try
            {
                BenefitDTO benefit = benefitService.Get(id);
                benefitService.Delete(benefit);
                return Json("OK");
            }
            catch { return Json("Error"); }
        }
    }
}

OSBB/Views/Benefit/Edit.cshtml
@model OSBB_BLL.Models.BenefitDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Редагування</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Пільга</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BenefitId)
        <div class="form-group">
            @Html.LabelFor(model => model.BenefitName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BenefitName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BenefitName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BenefitPercent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BenefitPercent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BenefitPercent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутись до списку", "Index", null, new { @class = "btn btn-primary"})
</div>

OSBB/Views/Benefit/Index.cshtml
@model IEnumerable<OSBB_BLL.Models.BenefitDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Пільги</h2>

<p>
    @Html.ActionLink("Додати", "Edit", new { id = 0 }, new { @class = "btn btn-primary"})
</p>
<table class="table table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BenefitName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BenefitPercent)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BenefitName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BenefitPercent)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.BenefitId }, new { @class = "btn-sm btn-primary fas fa-pencil-alt" })
            @Html.ActionLink(" ", "Delete", new { id = item.BenefitId }, new { @class = "btn-sm btn-primary fas fa-trash delBenefit", benefit_id = item.BenefitId})
        </td>
    </tr>
}

</table>

@section Scripts{
    <script type="text/javascript">

        $(function () {
            $(".delBenefit").click(function (e) {
                e.preventDefault()
                if (confirm('Дійсно видалити запис?')) {
                    $.ajax({
                        url: "@Url.Action("Delete", "Benefit")",
                        data: { id: $(this).attr('benefit-id') },
                        type: 'POST',
                        success: function (data) {
                            if (data == "OK")
                                window.location.href = "@Url.Action("Index", "Benefit")"
                            else
                                alert("Error")
                        },
                        error: function (data) {
                            alert(data)
                        }
                    });
                }
            });
        });

    </script>

    }