OSBB/Controllers/ApartmentController.cs
using OSBB_BLL.Models;
using OSBB_BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using OSBB.Models;

namespace OSBB.Controllers
{
    [Authorize(Roles = "OSBB_Admin")]
    public class ApartmentController : Controller
    {
        IGenericService<ApartmentDTO> apartmentService;
        IGenericService<BenefitDTO> benefitService;
        IGenericService<MonthPaymentDTO> paymentService;
        IGenericService<MonthPaymentsDetailDTO> paymentDetailService;
        IGenericService<UtilityDTO> utilityService;
        IEnumerable<AdminApartmentModel> viewApartment;

        public ApartmentController(IGenericService<ApartmentDTO> apartmentService, IGenericService<BenefitDTO> benefitService, 
            IGenericService<MonthPaymentDTO> paymentService, IGenericService<MonthPaymentsDetailDTO> paymentDetailService, IGenericService<UtilityDTO> utilityService)
        {
            this.apartmentService = apartmentService;
            this.benefitService = benefitService;
            this.paymentService = paymentService;
            this.paymentDetailService = paymentDetailService;
            this.utilityService = utilityService;
        }

        [HttpGet]
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            TempData["ApartmentId"] = null;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NumSortParam = String.IsNullOrEmpty(sortOrder) ? "num_desc" : "";
            ViewBag.OwnerSortParam = sortOrder == "Owner" ? "owner_desc" : "Owner";
            ViewBag.UsernameSortParam = sortOrder == "Username" ? "username_desc" : "Username";
            ViewBag.CurrentUtilSortParam = sortOrder == "CurrentUtil" ? "currentUtil_desc" : "CurrentUtil";

            if(searchString != null)
            {
                page = 1; 
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            viewApartment = new List<AdminApartmentModel>(apartmentService.GetAll().Select(a =>
            new AdminApartmentModel
            {
                ApartmentId = a.ApartmentId,
                ApartmentNumber = a.ApartmentNumber,
                OwnerName = a.OwnerName,
                Username = a.Username,
                HasCurrentUtil = paymentService.FindBy(p => p.ApartmentId == a.ApartmentId).Any(p => p.IsCurrent == 1)
            }));

            if (!String.IsNullOrEmpty(searchString))
            {
                viewApartment = viewApartment.Where(a => a.OwnerName.ToUpper().Contains(searchString.ToUpper())
                                            || a.ApartmentNumber.ToString().Equals(searchString));
            }

            switch(sortOrder)
            {
                case "num_desc":
                    viewApartment = viewApartment.OrderByDescending(a => a.ApartmentNumber);
                    break;
                case "Owner":
                    viewApartment = viewApartment.OrderBy(a => a.OwnerName);
                    break;
                case "owner_desc":
                    viewApartment = viewApartment.OrderByDescending(a => a.OwnerName);
                    break;
                case "Username":
                    viewApartment = viewApartment.OrderBy(a => a.Username);
                    break;
                case "username_desc":
                    viewApartment = viewApartment.OrderByDescending(a => a.Username);
                    break;
                case "CurrentUtil":
                    viewApartment = viewApartment.OrderBy(a => a.HasCurrentUtil);
                    break;
                case "currentUtil_desc":
                    viewApartment = viewApartment.OrderByDescending(a => a.HasCurrentUtil);
                    break;
                default:
                    viewApartment = viewApartment.OrderBy(a => a.ApartmentNumber);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            
            return View(viewApartment.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Edit (int id)
        {
            ApartmentDTO apartment = (id == 0) ? new ApartmentDTO() : apartmentService.Get(id);
            ViewBag.Benefits = new SelectList(benefitService.GetAll().Select(b => new SelectListItem { Value = b.BenefitId.ToString(), Text = b.BenefitName }), "Value", "Text",
                new SelectListItem { Value = apartment.BenefitId.ToString(), Text = apartment.BenefitName });
            return View(apartment);
        }

        [HttpPost]
        public ActionResult Edit (ApartmentDTO apartment)
        {
            if (ModelState.IsValid)
            {
                apartmentService.AddOrUpdate(apartment);
                return RedirectToAction("Index");
            }
            return View(apartment);
        }

        [HttpPost]
        public ActionResult Delete (int id)
        {
            try
            {
                ApartmentDTO apartment = apartmentService.Get(id);
                apartmentService.Delete(apartment);
                return Json("OK");
            }
            catch { return Json("Error"); }
        }

        [HttpGet]
        public ActionResult Details (int id)
        {
            return View(apartmentService.Get(id));
        }

        [HttpPost]
        public ActionResult ChangeMonth()
        {
            try
            {
                List<MonthPaymentDTO> apartments = paymentService.GetAll().Where(p => p.IsCurrent == 1).ToList();
                for(int i = 0; i < apartments.Count(); i++)
                {
                    apartments[i].IsCurrent = 0;
                    paymentService.AddOrUpdate(apartments[i]);
                }
                return Json("OK");
            }
            catch
            {
                return Json("Error");
            }

        }

        [HttpGet]
        public ActionResult CurrentUtil(int id)
        {
            TempData["ApartmentId"] = id;
            int curMonthId = paymentService.FindBy(p => p.ApartmentId == id).FirstOrDefault(p => p.IsCurrent == 1).MonthPaymentsId;
            ViewBag.Apartment = apartmentService.FindBy(ap => ap.ApartmentId == id).FirstOrDefault().ApartmentNumber;
            List<MonthPaymentsDetailDTO> payments = paymentDetailService.FindBy(d => d.MonthPaymentsId == curMonthId).ToList();

            return View(payments);
        }

        [HttpGet]
        public ActionResult AddRemoveUtilities (string action)
        {
            List<UtilityCheckListModel> checklist = new List<UtilityCheckListModel>();
            IEnumerable<UtilityDTO> utilities = utilityService.GetAll();
            ViewBag.Action = action;

            if(action == "add_all" || action == "del_all")
            {
                foreach (var util in utilities)
                {
                    if (util.UnitId == null)
                    {
                        checklist.Add(new UtilityCheckListModel
                        {
                            UtilityId = util.UtilityId,
                            UtilityName = util.UtilityName,
                            UtilityPrice = util.UtilityPrice,
                            IsChecked = false
                        });
                    }
                }

                return PartialView(checklist);
            }

            int apartmentId = (int)TempData["ApartmentId"];
            MonthPaymentDTO curMonth = paymentService.FindBy(p => p.ApartmentId == apartmentId).FirstOrDefault(p => p.IsCurrent == 1);
            IEnumerable<MonthPaymentsDetailDTO> curUtilities = paymentDetailService.FindBy(u => u.MonthPaymentsId == curMonth.MonthPaymentsId);

            if (action == "add")
            {
                foreach (var util in utilities)
                {
                    if (curUtilities.Any(u => u.UtilityId == util.UtilityId))
                        continue;
                    else
                    {
                        checklist.Add(new UtilityCheckListModel
                        {
                            UtilityId = util.UtilityId,
                            UtilityName = (util.UnitId == null) ? util.UtilityName : util.UtilityName + " (" + util.UnitName + ")",
                            UtilityPrice = util.UtilityPrice,
                            IsChecked = false
                        });
                    }
                }
            }
            else if (action == "del")
            {
                foreach (var util in utilities)
                {
                    if (curUtilities.Any(u => u.UtilityId == util.UtilityId))
                    {
                        checklist.Add(new UtilityCheckListModel
                        {
                            UtilityId = util.UtilityId,
                            UtilityName = (util.UnitId == null) ? util.UtilityName : util.UtilityName + " (" + util.UnitName + ")",
                            UtilityPrice = util.UtilityPrice,
                            IsChecked = false
                        });
                    }
                }
            }

            TempData["ApartmentId"] = apartmentId;
            return PartialView(checklist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRemoveUtilities(string action, List<UtilityCheckListModel> checklist)
        {
            if (checklist.Any(util => util.IsChecked) == false)
            {
                return View("Error");
            }

            if(action == "add")
            {
                int apartmentId = (int)TempData["ApartmentId"];
                MonthPaymentDTO curMonth = paymentService.FindBy(p => p.ApartmentId == apartmentId).FirstOrDefault(p => p.IsCurrent == 1);

OSBB/Views/Apartment/AddRemoveUtilities.cshtml
@model List<OSBB.Models.UtilityCheckListModel>

@using (Html.BeginForm("AddRemoveUtilities", "Apartment", FormMethod.Post))
{
    <input type="text" value="@ViewBag.Action" name="action" hidden/>
    @Html.AntiForgeryToken()
    <div class="container form-horizontal">
        <div class="form-group">
            @for (int i = 0; i < Model.Count(); i++)
            {
                <p>
                    @Html.HiddenFor(modelItem => Model[i].UtilityId)
                    @Html.CheckBoxFor(modelItem => Model[i].IsChecked)
                    @Html.DisplayFor(modelItem => Model[i].UtilityName)
                    @Html.HiddenFor(modelItem => Model[i].UtilityName)
                    @Html.HiddenFor(modelItem => Model[i].UtilityPrice)
                </p>
            }
        </div>
    </div>

    <div class="form-group">
        <div class="col-lg-offset-1">
            <input type="submit" value="Зберегти" class="btn btn-primary btn-block" />
        </div>
    </div>
}

OSBB/Views/Apartment/CurrentUtil.cshtml
@model IEnumerable<OSBB_BLL.Models.MonthPaymentsDetailDTO>

@{
    ViewBag.Title = "CurrentUtil";
}

<h2>Перелік послуг за звітний місяць</h2>
<h3>Квартира № @ViewBag.Apartment</h3>

<p>
    @Html.ActionLink("Додати", null, null, new { @class = "btn btn-primary col-lg-2 getUtilAdd" })
    @Html.ActionLink("Видалити", null, null, new { @class = "btn btn-primary col-lg-2 getUtilDel" })
</p>
<div class="bs-component">
    <div class="card border-primary" style="display:none;" id="utilListAdd">
        <div class="card-header">
            <h4 class="card-title">Оберіть послуги, які потрібно додати:</h4>
        </div>
        <div class="card-body">
            @Html.Action("AddRemoveUtilities", new { action = "add" })
        </div>
    </div>
</div>
<div class="bs-component">
    <div class="card border-primary" style="display:none;" id="utilListDel">
        <div class="card-header">
            <h4 class="card-title">Оберіть послуги, які потрібно видалити:</h4>
        </div>
        <div class="card-body">
            @Html.Action("AddRemoveUtilities", new { action = "del" })
        </div>
    </div>
</div>
<table class="table table-condensed table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UtilityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeterIndexStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeterIndexEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentSum)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @Html.HiddenFor(modelItem => item.MonthPaymentsDetailId)
            @Html.HiddenFor(modelItem => item.MonthPaymentsId)
            @Html.HiddenFor(modelItem => item.UtilityId)
            <td class="text-info">
                <b>@Html.DisplayFor(modelItem => item.UtilityName)</b>
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.MeterIndexStart)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.MeterIndexEnd)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.PaymentSum)
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Повернутися до списку квартир ", "Index", null, new { @class = "btn btn-primary" })
</p>

@section Scripts{
    <script>
        $(function () {
            $(".getUtilAdd").click(function (e) {
                e.preventDefault();
                $('#utilListDel').attr("style", "display:none;");
                $('#utilListAdd').attr("style", "display:inline-block;");
            });
        });
    </script>

    <script>
        $(function () {
            $(".getUtilDel").click(function (e) {
                e.preventDefault();
                $('#utilListAdd').attr("style", "display:none;");
                $('#utilListDel').attr("style", "display:inline-block;");
            });
        });
    </script>
}

OSBB/Views/Apartment/Details.cshtml
@model OSBB_BLL.Models.ApartmentDTO

@{
    ViewBag.Title = "Details";
}

<h2>Подробиці</h2>

<div>
    <h4>Квартира № @Model.ApartmentNumber</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApartmentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApartmentNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalSquare)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalSquare)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LivingSquare)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LivingSquare)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tenants)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenants)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BenefitName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BenefitName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редагувати", "Edit", new { id = Model.ApartmentId }, new { @class = "btn btn-primary"})
    @Html.ActionLink("Повернутися до списку", "Index", null, new { @class = "btn btn-primary"})
</p>

OSBB/Views/Apartment/Edit.cshtml
@model OSBB_BLL.Models.ApartmentDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Редагування</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Квартира</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ApartmentId)
    <div class="form-group">
        @Html.LabelFor(model => model.ApartmentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ApartmentNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ApartmentNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalSquare, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalSquare, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TotalSquare, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LivingSquare, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LivingSquare, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LivingSquare, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tenants, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tenants, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tenants, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BenefitId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.BenefitId, this.ViewBag.Benefits as SelectList, "Оберіть пільгу", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BenefitId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Зберегти" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index", null, new { @class = "btn btn-primary"})
</div>

OSBB/Views/Apartment/Index.cshtml
@model PagedList.IPagedList<OSBB.Models.AdminApartmentModel>

@{
    ViewBag.Title = "Index";
}

<h2>Список квартир</h2>

<p>
    @Html.ActionLink("Додати нову", "Edit", new { id = 0 }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Додати послуги", null, null, new { @class = "btn btn-primary getUtilAdd" })
    @Html.ActionLink("Видалити послуги", null, null, new { @class = "btn btn-primary getUtilDel" })
    @Html.ActionLink("Закрити період", "ChangeMonth", null, new { @class = "btn btn-primary changeMonth" })
</p>

<div class="bs-component">
    <div class="card border-primary" style="display:none;" id="utilListAdd">
        <div class="card-header">
            <h4 class="card-title">Оберіть послуги, які потрібно додати:</h4>
        </div>
        <div class="card-body">
            @Html.Action("AddRemoveUtilities", new { action = "add_all"})
        </div>
    </div>
</div>

<div class="bs-component">
    <div class="card border-primary" style="display:none;" id="utilListDel">
        <div class="card-header">
            <h4 class="card-title">Оберіть послуги, які потрібно додати:</h4>
        </div>
        <div class="card-body">
            @Html.Action("AddRemoveUtilities", new { action = "del_all" })
        </div>
    </div>
</div>

<div class="bs-component">
    @using (Html.BeginForm("Index", "Apartment", FormMethod.Get))
    {
    <div class="row" style="align-items:center; flex-direction:row">
        Пошук за ПІБ власника або номером квартири:
        <div class="col-md-6">
            @Html.TextBox("searchString", ViewBag.CurrentFilter as String, new { @class = "form-control" })
        </div>
        <div>
            <input type="submit" value="Шукати" class="btn-sm btn-primary" />
        </div>
    </div>
    }
</div>
    <div class="bs-component">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("Номер квартири", "Index", new { sortOrder = ViewBag.NumSortParam, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("ПІБ власника", "Index", new { sortOrder = ViewBag.OwnerSortParam, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("Користувач", "Index", new { sortOrder = ViewBag.UsernameSortParam, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink("Поточний місяць", "Index", new { sortOrder = ViewBag.CurrentUtilSortParam, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApartmentNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OwnerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Username)
                    </td>
                    <td align="left">
                        @if (item.HasCurrentUtil == true)
                        {
                            <a href="#" class="btn btn-default btn-xs disabled">
                                <span class="fas fa-check" style="color:green"></span>
                            </a>
                        }
                        else
                        {
                            <a href="#" class="btn btn-default btn-xs disabled">
                                <span class="fas fa-times" style="color:red"></span>
                            </a>
                        }
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Edit", new { id = item.ApartmentId }, new { @class = "btn-sm btn-primary fas fa-pencil-alt" })
                        @Html.ActionLink(" ", "Delete", new { id = item.ApartmentId }, new { @class = "btn-sm btn-primary fas fa-trash delApartment", apartment_id = item.ApartmentId })
                        @Html.ActionLink(" ", "Details", new { id = item.ApartmentId }, new { @class = "btn-sm btn-primary fas fa-info-circle" })
                        @if (item.HasCurrentUtil == true)
                        {
                            @Html.ActionLink(" ", "CurrentUtil", new { id = item.ApartmentId }, new { @class = "btn-sm btn-primary fas fa-clipboard-list" })
                        }
                    </td>
                </tr>
                }
            </tbody>

        </table>
    </div>

    <div>
        <ul class="pagination">
            @for (var i = 1; i <= Model.PageCount; i++)
            {
            <li class="page-item @(i == Model.PageNumber ? "disabled" : "")">
                @Html.ActionLink(i.ToString(), "Index", new { page = i, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }, new { @class = "page-link"})
            </li>
            }
        </ul>
    </div>

@section Scripts{

    <script type="text/javascript">

        $(function () {
            $(".delApartment").click(function (e) {
                e.preventDefault()
                if (confirm('Дійсно видалити запис?')) {
                    $.ajax({
                        url: "@Url.Action("Delete", "Apartment")",
                        data: { id: $(this).attr('apartment-id') },
                        type: 'POST',
                        success: function (data) {
                            if (data = "OK")
                                window.location.href = "@Url.Action("Index", "Apartment")"
                            else
                                alert("Error")
                        },
                        error: function (data) {
                            alert(data);
                        }
                    });
                }
            });
        });


                $(function () {
            $(".changeMonth").click(function (e) {
                e.preventDefault()
                if (confirm('Ви дійсно хочете змінити звітний період?')) {
                    $.ajax({
                        url: "@Url.Action("ChangeMonth", "Apartment")",
                        type: 'POST',
                        success: function (data) {
                            if (data = "OK")
                                window.location.href = "@Url.Action("Index", "Apartment")"
                            else
                                alert("Error")
                        },
                        error: function (data) {
                            alert(data);
                        }
                    });
                }
            });
        });



        $(function () {
            $(".getUtilAdd").click(function (e) {
                e.preventDefault();
                $('#utilListDel').attr("style", "display:none;");
                $('#utilListAdd').attr("style", "display:inline-block;");
            });
        });

        $(function () {
            $(".getUtilDel").click(function (e) {
                e.preventDefault();
                $('#utilListAdd').attr("style", "display:none;");
                $('#utilListDel').attr("style", "display:inline-block;");
            });
        });

    </script>

}