OSBB/Controllers/PersonalAccountController.cs
using OSBB.Models;
using OSBB_BLL.Models;
using OSBB_BLL.Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OSBB.Controllers
{
    [Authorize]
    public class PersonalAccountController : Controller
    {
        UserPrivateAccount account;
        IGenericService<MonthPaymentDTO> paymentService;
        IGenericService<MonthPaymentsDetailDTO> paymentDetailService;
        IGenericService<ApartmentDTO> apartmentService;
        IGenericService<UtilityDTO> utilityService;
        IGenericService<BenefitDTO> benefitService;

        public PersonalAccountController(IGenericService<MonthPaymentDTO> paymentService,
        IGenericService<MonthPaymentsDetailDTO> paymentDetailService, IGenericService<ApartmentDTO> apartmentService, 
        IGenericService<UtilityDTO> utilityService, IGenericService<BenefitDTO> benefitService)
        {
            this.paymentService = paymentService;
            this.paymentDetailService = paymentDetailService;
            this.apartmentService = apartmentService;
            this.utilityService = utilityService;
            this.benefitService = benefitService;
            account = new UserPrivateAccount();
        }
        
        [HttpGet]
        public ActionResult Index (int monthId = 0)
        {
            account.ApartmentId = apartmentService.FindBy(ap => ap.Username == User.Identity.Name).FirstOrDefault().ApartmentId;
            ViewBag.ApartmentNumber = apartmentService.Get(account.ApartmentId).ApartmentNumber;
            ViewBag.AccountNumber = apartmentService.Get(account.ApartmentId).AccountNumber;

            account.AvailableMonths = new SelectList(paymentService.FindBy(p => p.ApartmentId == account.ApartmentId).Select(m => new SelectListItem
            {
                Value = m.MonthPaymentsNum.ToString(),
                Text = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(m.MonthPaymentsNum)
            }), "Value", "Text");

            account.SelectedMonth = (monthId == 0) ? GetPreviousMonth(DateTime.Now.Month) : monthId;
            account.HasBenefit = (apartmentService.Get(account.ApartmentId).BenefitId == null) ? false : true;

            if (account.HasBenefit)
            {
                ViewBag.Benefit = benefitService.Get((int)apartmentService.Get(account.ApartmentId).BenefitId).BenefitName;
            }
            
            account.HasCurrent = paymentService.FindBy(p => p.ApartmentId == account.ApartmentId).Any(m => m.IsCurrent == 1);
            if (account.HasCurrent)
            {
                account.CurrentMonth = paymentService.FindBy(p => p.ApartmentId == account.ApartmentId).FirstOrDefault(m => m.IsCurrent == 1).MonthPaymentsNum;
            }

            if (paymentService.FindBy(p => p.ApartmentId == account.ApartmentId).Any(m => m.MonthPaymentsNum == account.SelectedMonth))
            {
                account.MonthPaymentsId = paymentService.FindBy(p => p.ApartmentId == account.ApartmentId).FirstOrDefault(m => m.MonthPaymentsNum == account.SelectedMonth).MonthPaymentsId;
                account.Utilities = paymentDetailService.FindBy(d => d.MonthPaymentsId == account.MonthPaymentsId).ToList();
            }

            Session["account"] = account;

            return View(account);
        }

        [HttpGet]
        public ActionResult AddCurrentUtilities()
        {
            List<UtilityCheckListModel> checklist = new List<UtilityCheckListModel>();
            IEnumerable<UtilityDTO> utilities = utilityService.GetAll().Where(u => u.UnitId != null);

            foreach (var util in utilities)
            {
                checklist.Add(new UtilityCheckListModel
                {
                    UtilityId = util.UtilityId,
                    UtilityName = util.UtilityName + " (" + util.UnitName + ")",
                    UtilityPrice = util.UtilityPrice,
                    IsChecked = false
                });
            }

            return PartialView(checklist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCurrentUtilities(List<UtilityCheckListModel> checklist)
        {
            if(checklist.Any(util => util.IsChecked) == false)
            {
                return RedirectToAction("Index");
            }

            account = (UserPrivateAccount)Session["account"];

            MonthPaymentDTO currentMonth = paymentService.AddOrUpdate(new MonthPaymentDTO
            {
                MonthPaymentsNum = GetPreviousMonth(DateTime.Now.Month),
                ApartmentId = account.ApartmentId,
                IsCurrent = 1
            });

            int previousMonthNum = GetPreviousMonth(currentMonth.MonthPaymentsNum);
            MonthPaymentDTO previousMonth = paymentService.FindBy(m => m.MonthPaymentsNum == previousMonthNum).FirstOrDefault(a => a.ApartmentId == account.ApartmentId);

            if (previousMonth != null)
            {
                foreach (var util in checklist)
                {
                    if (util.IsChecked)
                    {
                        MonthPaymentsDetailDTO paymentsDetail = paymentDetailService.AddOrUpdate(new MonthPaymentsDetailDTO
                        {
                            MonthPaymentsId = currentMonth.MonthPaymentsId,
                            UtilityId = util.UtilityId,
                            MeterIndexStart = CheckPreviousMonthMeter(previousMonth.MonthPaymentsId, util.UtilityId),
                            PaymentSum = 0
                        });
                    }
                }
            }
            else
            {
                foreach (var util in checklist)
                {
                    if (util.IsChecked)
                    {
                        MonthPaymentsDetailDTO paymentsDetail = paymentDetailService.AddOrUpdate(new MonthPaymentsDetailDTO
                        {
                            MonthPaymentsId = currentMonth.MonthPaymentsId,
                            UtilityId = util.UtilityId,
                            MeterIndexStart = 0,
                            PaymentSum = 0
                        });
                    }
                }
            }

            Session["account"] = account;

            return RedirectToAction("Edit", new { id = currentMonth.MonthPaymentsId });
        }

        private int CheckPreviousMonthMeter(int monthPaymentsId, int utilityId)
        {
            MonthPaymentsDetailDTO previousUtilityDetail = paymentDetailService.FindBy(p => p.MonthPaymentsId == monthPaymentsId).FirstOrDefault(u => u.UtilityId == utilityId);

            if (previousUtilityDetail != null && previousUtilityDetail.MeterIndexEnd != null)
                return (int)previousUtilityDetail.MeterIndexEnd;

            return 0;
        }

        private int GetPreviousMonth (int month)
        {
            if (month == 1)
                return 12;
            else
                return month - 1;
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            MonthPaymentDTO monthPayment = paymentService.Get(id);
            List<MonthPaymentsDetailDTO> paymentDetails = paymentDetailService.FindBy(d => d.MonthPaymentsId == monthPayment.MonthPaymentsId).ToList();
            ViewBag.MonthNum = monthPayment.MonthPaymentsNum;

            return View(paymentDetails);
        }

        [HttpPost]
        public ActionResult Edit(List<MonthPaymentsDetailDTO> payments)
        {
            int month = 0;
            account = (UserPrivateAccount)Session["account"];

            if (ModelState.IsValid)
            {
                foreach (var payment in payments)
                {
                    if(payment.MeterIndexEnd < payment.MeterIndexStart)
                    {
                        ModelState.AddModelError("", "Показник на кінець періоду не може бути меншим за показник на початок!");
                        return View(payments);
                    }

                    decimal discount = 0;

                    if (account.HasBenefit)
                    {
                        int benefit = benefitService.Get((int)apartmentService.Get(account.ApartmentId).BenefitId).BenefitPercent;
                        decimal utilNorm = utilityService.Get(payment.UtilityId).UtilityNorm;
                        discount = (decimal)apartmentService.Get(account.ApartmentId).Tenants * utilNorm * ((decimal)benefit / 100);
                    }

                    account.CheckPaymentSum(payment, discount);
                    paymentDetailService.AddOrUpdate(payment);
                    month = paymentService.FindBy(p => p.MonthPaymentsId == payment.MonthPaymentsId).FirstOrDefault().MonthPaymentsNum;
                }

                return RedirectToAction("Index", new { monthId = month });
            }

            Session["account"] = account;

            return View(payments);
        }

    }
}

OSBB/Views/PersonalAccount/AddCurrentUtilities.cshtml
@model List<OSBB.Models.UtilityCheckListModel>

@using (Html.BeginForm("AddCurrentUtilities", "PersonalAccount", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container form-horizontal">
            <div class="form-group">
                @for (int i = 0; i < Model.Count(); i++)
                {
                <p>
                    @Html.HiddenFor(modelItem => Model[i].UtilityId)
                    @Html.CheckBoxFor(modelItem => Model[i].IsChecked)
                    @Html.DisplayFor(modelItem => Model[i].UtilityName)
                    @Html.HiddenFor(modelItem => Model[i].UtilityName)
                    @Html.HiddenFor(modelItem => Model[i].UtilityPrice)
                </p>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-offset-1">
                <input type="submit" value="Зберегти" class="btn btn-primary btn-block" />
            </div>
        </div>
    }

OSBB/Views/PersonalAccount/Edit.cshtml
@model List<OSBB_BLL.Models.MonthPaymentsDetailDTO>

@{
    ViewBag.Title = "Edit";
}

<h2>Редагування показників</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="bs-component">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @for (int i = 0; i < Model.Count(); i++)
        {
            if (Model[i].MeterIndexStart != null)
            {
                    <div class="card border-primary">
                        <div class="card-header text-white bg-primary">
                            <h5>@Model[i].UtilityName</h5>
                        </div>

                        @Html.HiddenFor(model => Model[i].MonthPaymentsDetailId)
                        @Html.HiddenFor(model => Model[i].MonthPaymentsId)
                        @Html.HiddenFor(model => Model[i].UtilityId)
                        @Html.HiddenFor(model => Model[i].MeterIndexStart)
                        @Html.HiddenFor(model => Model[i].UtilityName)
                        @Html.HiddenFor(model => Model[i].UtilityPrice)

                        <table class="table table-condensed" style="margin-bottom:0px">
                            <tr>
                                <th>
                                    @Html.LabelFor(model => Model[i].MeterIndexStart, htmlAttributes: new { @class = "control-label" })
                                </th>
                                <th>
                                    @Html.LabelFor(model => Model[i].MeterIndexEnd, htmlAttributes: new { @class = "control-label" })
                                    
                                </th>
                            </tr>
                            <tr>
                                <td align="center">
                                    @Html.DisplayFor(model => Model[i].MeterIndexStart, new { htmlAttributes = new { @class = "form-control" } })
                                </td>
                                <td align="center">
                                    @Html.EditorFor(model => Model[i].MeterIndexEnd, new { htmlAttributes = new { @class = "form-control text-danger" } })
                                    @Html.ValidationMessageFor(model => Model[i].MeterIndexEnd, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                        </table>
                    </div>
            }
        }
        <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-success col-lg-3" />
        </div>
    </div>
</div>
}

    <div>
        @Html.ActionLink("Повернутися до загального списку", "Index", new { monthId = ViewBag.MonthNum }, new { @class = "btn btn-primary col-lg-3" })
    </div>

OSBB/Views/PersonalAccount/GetListUtilities.cshtml
@model IEnumerable<OSBB_BLL.Models.UtilityDTO>

<form>
    @foreach (var item in Model)
    {
    <label class="checkbox-inline">
        <input type="checkbox" value="@item.UtilityId" />
        @item.UtilityName (@item.UnitName)
    </label>
    }
</form>

OSBB/Views/PersonalAccount/Index.cshtml
@model OSBB.Models.UserPrivateAccount

@{
    ViewBag.Title = "Index";
}

<h2>Особистий кабінет</h2>

<div>
    <h4>Квартира № @ViewBag.ApartmentNumber, О/Р № @ViewBag.AccountNumber</h4>
    <hr />
    @if (Model.HasBenefit)
    {
        <div class="alert alert-dismissible alert-primary">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Увага!</strong> Розрахунок сум здійснено з урахуванням вашої пільги - @ViewBag.Benefit.
        </div>
    }
    @Html.HiddenFor(model => model.MonthPaymentsId)
    <div class="row paymentDetails" style="align-items:center">
        <div class="dropdown col-lg-5">
            <div cass="bs-component">
                <h4>
                    Комунальні послуги за:
                    @Html.DropDownListFor(model => model.SelectedMonth, Model.AvailableMonths as SelectList, "Оберіть місяць", new { @class = "btn btn-default col-lg-5 border-secondary dropdown-toggle form-control monthsList", month_id = Model.SelectedMonth })
                </h4>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="bs-component">
                <h4>
                    @Html.DisplayNameFor(model => model.TotalCost)
                    <b class="text-info">@Html.DisplayFor(model => model.TotalCost)</b>
                </h4>
            </div>
        </div>
        <div class="col-lg-4 bs-component">
            @if (Model.HasCurrent == true && Model.CurrentMonth == Model.SelectedMonth)
            {
                <div>
                    @Html.ActionLink("Редагувати дані", "Edit", "PersonalAccount", new { id = Model.MonthPaymentsId }, new { @class = "btn btn-primary" })
                </div>
            }
            else if (Model.HasCurrent == false)
            {
                <div>
                    @Html.ActionLink("Внести дані за звітний період", null, null, null, new { @class = "btn btn-primary getUtil" })
                </div>
            }
        </div>
    </div>
    <br />
    <div class="bs-component">
        <div class="card border-primary" style="display:none;" id="utilList">
            <div class="card-header">
                <h4 class="card-title">Оберіть послуги, за якими треба внести показники:</h4>
            </div>
            <div class="card-body">
                @Html.Action("AddCurrentUtilities")
            </div>
        </div>
    </div>
    <br />
    <div class="container">
        <div class="bs-component">
            @foreach (var util in Model.Utilities)
            {
                <div class="card border-primary">
                    <div class="card-header text-white bg-primary">
                        <h5>@util.UtilityName</h5>
                    </div>
                    <table class="table table-bordered table-condensed" style="margin-bottom:0px">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => util.MeterIndexStart)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => util.MeterIndexEnd)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => util.PaymentSum)
                            </th>
                        </tr>
                        <tr>
                            <td align="center">
                                @Html.DisplayFor(model => util.MeterIndexStart)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(model => util.MeterIndexEnd)
                            </td>
                            <td class="text-info" align="center">
                                <b>@Html.DisplayFor(model => util.PaymentSum)</b>
                            </td>
                        </tr>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $(".monthsList").change(function () {
                var monthId = $(this).val();
                window.location.href = '@Url.Action("Index", "PersonalAccount")' + '?monthId=' + monthId;
            });
        });

    </script>

    <script>
        $(function () {
            $(".getUtil").click(function (e) {
                e.preventDefault();
                $('#utilList').attr("style","display:inline-block;");
            });
        });
    </script>
}

OSBB/Views/PersonalAccount/IndexDetails.cshtml
@model OSBB.Models.UserPrivateAccount

@foreach (var util in Model.Utilities)
{
    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h5 class="panel-title">@util.UtilityName</h5>
            </div>
            <div class="panel-body">
                <div class="col-md-5 text-center">
                    @Html.DisplayNameFor(model => util.MeterIndexStart)<br />
                    <b>@Html.DisplayFor(model => util.MeterIndexStart)</b>
                </div>
                <div class="col-md-5 text-center">
                    @Html.DisplayNameFor(model => util.MeterIndexEnd)<br />
                    <b>@Html.DisplayFor(model => util.MeterIndexEnd)</b>
                </div>
                <div class="col-md-2 text-center">
                    @Html.DisplayNameFor(model => util.PaymentSum)<br />
                    <b>@Html.DisplayFor(model => util.PaymentSum)</b>
                </div>
            </div>
        </div>
    </div>
}