OSBB/Controllers/UtilityController.cs
using OSBB_BLL.Models;
using OSBB_BLL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OSBB.Controllers
{
    [Authorize(Roles = "OSBB_Admin")]
    public class UtilityController : Controller
    {
        IGenericService<UtilityDTO> utilityService;
        IGenericService<UnitDTO> unitService;

        public UtilityController(IGenericService<UtilityDTO> utilityService, IGenericService<UnitDTO> unitService)
        {
            this.utilityService = utilityService;
            this.unitService = unitService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(utilityService.GetAll());
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            UtilityDTO utility = (id == 0) ? new UtilityDTO() : utilityService.Get(id);
            ViewBag.Units = new SelectList(unitService.GetAll().Select(u => new SelectListItem { Value = u.UnitId.ToString(), Text = u.UnitName }), "Value", "Text", 
                new SelectListItem { Value = utility.UnitId.ToString(), Text = utility.UnitName });
            return View(utility);
        }

        [HttpPost]
        public ActionResult Edit (UtilityDTO utility)
        {
            if (ModelState.IsValid)
            {
                utilityService.AddOrUpdate(utility);
                return RedirectToAction("Index");
            }
            return View(utility);
        }

        [HttpPost]
        public ActionResult Delete (int id)
        {
            try
            {
                UtilityDTO utility = utilityService.Get(id);
                utilityService.Delete(utility);
                return Json("OK");
            }
            catch { return Json("Error"); }
        }
    }
}

OSBB/Views/Utility/Edit.cshtml
@model OSBB_BLL.Models.UtilityDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Редагування</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Послуга</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UtilityId)
    <div class="form-group">
        @Html.LabelFor(model => model.UtilityName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UtilityName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UtilityName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.UnitId, this.ViewBag.Units as SelectList, "Оберіть одиницю виміру", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UnitId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UtilityPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UtilityPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UtilityPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UtilityNorm, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UtilityNorm, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UtilityNorm, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Зберегти" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index", null, new { @class = "btn btn-primary"})
</div>

OSBB/Views/Utility/Index.cshtml
@model IEnumerable<OSBB_BLL.Models.UtilityDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Послуги</h2>

<p>
    @Html.ActionLink("Додати", "Edit", new { id = 0 }, new { @class = "btn btn-primary"})
</p>
<table class="table table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UtilityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UtilityPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UtilityNorm)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UtilityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UtilityPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UtilityNorm)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.UtilityId }, new { @class = "btn-sm btn-primary fas fa-pencil-alt" })
            @Html.ActionLink(" ", "Delete", new { id = item.UtilityId }, new { @class = "btn-sm btn-primary fas fa-trash delUtility", utility_id = item.UtilityId })
        </td>
    </tr>
}

</table>

@section Scripts{
    
    <script type="text/javascript">

        $(function () {
            $(".delUtility").click(function (e) {
                e.preventDefault()
                if (confirm('Дійсно видалити запис?')) {
                    $.ajax({
                        url: "@Url.Action("Delete", "Utility")",
                        data: { id: $(this).attr('utility-id') },
                        type: 'POST',
                        success: function (data) {
                            if (data == "OK")
                                window.location.href = "@Url.Action("Index", "Utility")"
                            else
                                alert("Error")
                        },
                        error: function (data) {
                            alert(data)
                        }
                    });
                }
            });
        });
        
    </script>
    
    }